# Generated by Django 5.2.12 on 2026-03-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('adoption_status', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_ln_1', models.CharField(max_length=200)),
                ('address_ln_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('visiting_hours', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('veterinarian', models.CharField(blank=True, max_length=100)),
                ('pet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pet_directory_app.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pet_directory_app.shelter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pet_directory_app.species'),
        ),
    ]
